### ISSUE TITLE
clarifying use of "massNorm" in Form Factor calculation example

### ISSUE THREAD

**Issue by js54434** [neutronpy/neutronpy#103]
The examples for Form Factor calculations in http://neutronpy.github.io/reference/examples/material.html use massNorm set to True, but for the static nuclear structure factor this should be set to False to get a structure factor in units of barns. Is there a reason massNorm is set to True?

**Comment by pseudocubic** [comment]
`massNorm` is useful for getting the one-phonon inelastic cross-section, which depends on the nuclear structure factor in which the coherent scattering length is normalized by the square-root of masses of the atoms in the unit cell, see **Eq. 4.88** in "_Theory of neutron scattering from condensed matter, Volume 1_" by Stephen W. Lovesey.

I agree that this is confusing, particularly in the example file you linked, so I will update the documentation to make the usage more clear.
