### ISSUE TITLE
"mode" keyword no longer works for neutronpy.load(...)

### ISSUE THREAD

**Issue by js54434** [neutronpy/neutronpy#21]
If I execute
 `data1 = neutronpy.load(filename1, mode='ICP')` 
I get
`TypeError: load() got an unexpected keyword argument 'mode'`
The data seems to load fine without the "mode" keyword, though.

**Comment by pseudocubic** [comment]
Sorry, that's an error in the documentation. The new keyword is filetype for the load() function. It is correct in the auto-generated function reference, but I neglected to update it in the Example.

**Comment by pseudocubic** [comment]
Addressed by 6fcc34c51eb7e351164fb839591bc6dfe1ef8432
