### ISSUE TITLE
vmosaic keyword argument not accepted in Sample class

### ISSUE THREAD

**Issue by js54434** [neutronpy/neutronpy#50]
I'm trying to compare a different resolution matrix calculation code with the neutronpy calculation, but I'm noticing that, while vmosaic is mentioned in the source code for the Instrument class, it's not yet a part of the Sample class.

**Comment by pseudocubic** [comment]
The calculation takes into account a `vmosaic` attribute of the Sample class if it has one, which you can define if you wish, but you are correct that I never explicitly included the `vmosaic` attribute in `Sample`, so I will correct that.
