### ISSUE TITLE
default moncor setting opposite of what's in documentation

### ISSUE THREAD

**Issue by js54434** [neutronpy/neutronpy#51]
If I do a resolution calculation and set moncor=1 in the Instrument class, I get a different R0 value than I do if I omit moncor, which happens to be the same value as for moncor=0. This is backwards from what's described on [this page](http://neutronpy.github.io/reference/generated/neutronpy.resolution.Instrument.moncor.html#neutronpy.resolution.Instrument.moncor) in the documentation.

**Comment by pseudocubic** [comment]
The problem is in line 1420. It should set `moncor=1` there, but sets it to zero by default.
