### ISSUE TITLE
wrong error displayed for Q range too large for given Ei, Ef

### ISSUE THREAD

**Issue by js54434** [neutronpy/neutronpy#61]
If my Q-range is too large for the given Ei and Ef, then I get the error
```ValueError: array must not contain infs or NaNs```
but from the code in resolution.py, it seems that this is the error that's supposed to be printed:
```
s2theta = np.arccos((ki ** 2 + kf ** 2 - q ** 2) / (2. * ki * kf)) * ss  # * np.sign(em)  # ss  # 2theta sample @IgnorePep8
if np.iscomplex(s2theta):
    raise ValueError(': KI,KF,Q triangle will not close (kinematic equations). Change the value of KFIX,FX,QH,QK or QL.')
```
This is probably because the arccos returns a NaN rather than a complex number.

**Comment by pseudocubic** [comment]
My initial thought is that from the numpy documentation, `arccos` seems to always return a real number if the input is real, but want it to return a complex number.
